name: CI-pre-merge
on:
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on:
    - ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '16'
    - name: Run test
      run: |
        npm install -g yarn
        rm -rf node_modules && yarn install
        yarn test
  lint:
    runs-on:
    - ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
    - run: |
        npm install -g yarn
        rm -rf node_modules && yarn install
    - run: yarn run lint

